services:
  wp_db:
    image: mariadb:11
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - wp_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress

  wp:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=wp_db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

volumes:
  wp_data:
  wp_db_data:
